#Prediction without Pipeline

In [13]:
import pickle
import numpy as np

In [14]:
ohe_sex = pickle.load(open('models/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('models/ohe_embarked.pkl','rb'))
clf = pickle.load(open('models/clf.pkl','rb'))

In [15]:
test_input = np.array([2,'male',31.0,0,0,10.5,'S'],dtype = object).reshape(1,7)

In [16]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [17]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [18]:
test_input_embarked = ohe_embarked.transform(test_input[:,1].reshape(1,1))

In [19]:
test_input_age = test_input[:,2].reshape(1,1)

In [20]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis = 1)

In [21]:
test_input_transformed.shape

(1, 10)

In [22]:
clf.predict(test_input_transformed)

array([1])

#Prediction with Pipeline

In [23]:
pipe = pickle.load(open('pipe.pkl','rb'))

In [26]:
test_input2 = np.array([2,'male',31.0,0,0,10.5,'S'],dtype = object).reshape(1,7)

In [27]:
pipe.predict(test_input2)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(


array([0])